name: Get Branch Protection Rules

# TODO: It would be great to schedule this like once a week/day to get the most current info on the rules
# TODO: Specifically all rules, and update a file with that info.
# TODO: In regards to the schedule, this should be a configurable input if this were a Marketplace Action
# TODO: In the same vein, the filepath should also be user configurable if this were a Marketplace Action.
# Man I am too good. How did I get both of those lines to be the same length 

on:

  # This workflow should only ever be run manually from the Actions tab
  workflow_dispatch:
    inputs:
      get_rules_for:
        description: Name of branch to check for protection rules
        required: true
        type: choice
        options: 
          - 'all branches with rules'
          - 'main'
          - 'env/qa1'
        default: 'all branches with rules'
      verbose:
        description: Verbose (shows several print statements for additional info/debugging)
        required: true
        type: boolean
        default: false

jobs:
  get-branch-protection-rules:
    name: Get Branch Protection Rules (Job)
    runs-on: ubuntu-latest
    permissions: 
      contents: read
    env:
      GET_RULES_FOR: ${{github.event.inputs.get_rules_for}}
      GH_TOKEN: ${{ github.token }}
      REPO_READ_TOKEN: ${{ secrets.REPO_ADMIN_READ }}
      ORG: ${{ github.repository_owner }}
      VERBOSE: ${{github.event.inputs.verbose}}
    steps:
      - uses: actions/checkout@v4

      - name: Verbose testing
        run: echo "VERBOSE = $VERBOSE"
      
      - name: Make shell scripts executable
        run: chmod +x ./shell-scripts/*.sh # Gives execute permissions to the script
      
      - name: Run get-branch-prot-rules script
        run: ./shell-scripts/get-branch-prot-rules.sh 
