name: Get Branch Protection Rules

on:

  # This workflow should only ever be run manually from the Actions tab
  workflow_dispatch:
    inputs:
      get_rules_for:
        description: Name of branch to check for protection rules
        required: true
        type: choice
        options: 
          - 'all branches with rules'
          - 'main'
          - 'env/qa1'
        default: 'all branches with rules'

jobs:
  get-branch-protection-rules:
    name: Get Branch Protection Rules (Job)
    runs-on: ubuntu-latest
    permissions: 
      contents: read
    env:
      GET_RULES_FOR: ${{github.event.inputs.get_rules_for}}
      GH_TOKEN: ${{ github.token }}
      REPO_READ_TOKEN: ${{ secrets.REPO_ADMIN_READ }}
      ORG: ${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Make shell scripts executable
        run: chmod +x ./shell-scripts/*.sh # Gives execute permissions to the script
      
      - name: Run get-branch-prot-rules script
        run: ./shell-scripts/get-branch-prot-rules.sh 
