# Informative: This is a basic workflow to help you get started with Actions

#The name at top-level gives the job a name that is seen in the Actions tab.
name: Test Github Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # 8-28-25: These should probably be commented back in at some point, but I'm doing PR related testing and this is just static.
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test-job"
  test-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: "33"
      COMMENT_URL: "https://api.github.com/repos/${{github.repository}}/issues/NUM/comments"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Pretty much all Github Actions need and utilize this
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell. The usage of the pipe | is necessary
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Shows how the variables described in job-level env can be used by subsequent steps   
      - name: Echo job env vars
        run: |
          echo "PR_NUMBER = $PR_NUMBER"
          echo "$ {PR_NUMBER} = ${PR_NUMBER}"

      # Shows how to 
      - name: Modify COMMENT_URL    
        run: |  
          echo "URL before:  $COMMENT_URL"
          COMMENT_URL="${COMMENT_URL/NUM/$PR_NUMBER}"
          echo "URL after:  $COMMENT_URL"
      
      - name: Echo COMMENT_URL after modification in different step
        run: echo $COMMENT_URL

      - name: Make shell scripts executable
        run: chmod +x ./shell-scripts/*.sh # Gives execute permissions to the script
      
        # Example of how to run a shell script from within a workflow
      - name: Run the say-hello.sh shell script
        run: ./shell-scripts/say-hello.sh
      
      - name: State the organization
        run: echo "The organization name is:${{github.repository_owner}}"

      - name: State the teams in this organization
        run: echo "TODO Teams TBD"

      # GITHUB_WORKSPACE is an environmental variable whose value is the default working directory on the runner for steps 
      # This is also the default location of your repository when using the checkout action. Ex. /home/runner/work/bash-git-script/bash-git-script
      - name: State GITHUB_WORKSPACE var
        run: echo "Github Workspace = $GITHUB_WORKSPACE"
